taco:
  orders:
    ordersListLength: 20
spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    initialization-mode: always
logging:
  level:
    tacos: DEBUG
#---
#spring:
#  profiles: prod
#logging:
#  level:
#    tacos: WARN